<?php

namespace Container6FtKo6Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDemandeControllerrefuserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tqdr_iW.App\Controller\AdminDemandeController::refuser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.tqdr_iW'] ?? $container->load('get_ServiceLocator_TqdrIWService'));

        if (isset($container->privates['.service_locator.tqdr_iW.App\\Controller\\AdminDemandeController::refuser()'])) {
            return $container->privates['.service_locator.tqdr_iW.App\\Controller\\AdminDemandeController::refuser()'];
        }

        $instance = $a->withContext('App\\Controller\\AdminDemandeController::refuser()', $container);

        if (isset($container->privates['.service_locator.tqdr_iW.App\\Controller\\AdminDemandeController::refuser()'])) {
            return $container->privates['.service_locator.tqdr_iW.App\\Controller\\AdminDemandeController::refuser()'];
        }

        return $container->privates['.service_locator.tqdr_iW.App\\Controller\\AdminDemandeController::refuser()'] = $instance;
    }
}
