<?php

namespace Container6FtKo6Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tqdr_iW.App\Entity\DemandeReservation' shared service.
     *
     * @return \App\Entity\DemandeReservation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tqdr_iW": it needs an instance of "App\\Entity\\DemandeReservation" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
