<?php

namespace Container6FtKo6Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskApiControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0MKPK3c.App\Controller\Api\TaskApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.0MKPK3c'] ?? $container->load('get_ServiceLocator_0MKPK3cService'));

        if (isset($container->privates['.service_locator.0MKPK3c.App\\Controller\\Api\\TaskApiController::update()'])) {
            return $container->privates['.service_locator.0MKPK3c.App\\Controller\\Api\\TaskApiController::update()'];
        }

        $instance = $a->withContext('App\\Controller\\Api\\TaskApiController::update()', $container);

        if (isset($container->privates['.service_locator.0MKPK3c.App\\Controller\\Api\\TaskApiController::update()'])) {
            return $container->privates['.service_locator.0MKPK3c.App\\Controller\\Api\\TaskApiController::update()'];
        }

        return $container->privates['.service_locator.0MKPK3c.App\\Controller\\Api\\TaskApiController::update()'] = $instance;
    }
}
