<?php

namespace ContainerNqqUj7C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSalleControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WbJQk76.App\Controller\AdminSalleController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WbJQk76.App\\Controller\\AdminSalleController::delete()'] = ($container->privates['.service_locator.WbJQk76'] ?? $container->load('get_ServiceLocator_WbJQk76Service'))->withContext('App\\Controller\\AdminSalleController::delete()', $container);
    }
}
