<?php

namespace ContainerNqqUj7C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventApiControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AJCrrkc.App\Controller\Api\EventApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.AJCrrkc'] ?? $container->load('get_ServiceLocator_AJCrrkcService'));

        if (isset($container->privates['.service_locator.AJCrrkc.App\\Controller\\Api\\EventApiController::update()'])) {
            return $container->privates['.service_locator.AJCrrkc.App\\Controller\\Api\\EventApiController::update()'];
        }

        $instance = $a->withContext('App\\Controller\\Api\\EventApiController::update()', $container);

        if (isset($container->privates['.service_locator.AJCrrkc.App\\Controller\\Api\\EventApiController::update()'])) {
            return $container->privates['.service_locator.AJCrrkc.App\\Controller\\Api\\EventApiController::update()'];
        }

        return $container->privates['.service_locator.AJCrrkc.App\\Controller\\Api\\EventApiController::update()'] = $instance;
    }
}
