<?php

namespace ContainerNqqUj7C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementsControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ekf188_.App\Controller\EvenementsController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Ekf188_'] ?? $container->load('get_ServiceLocator_Ekf188Service'));

        if (isset($container->privates['.service_locator.Ekf188_.App\\Controller\\EvenementsController::new()'])) {
            return $container->privates['.service_locator.Ekf188_.App\\Controller\\EvenementsController::new()'];
        }

        $instance = $a->withContext('App\\Controller\\EvenementsController::new()', $container);

        if (isset($container->privates['.service_locator.Ekf188_.App\\Controller\\EvenementsController::new()'])) {
            return $container->privates['.service_locator.Ekf188_.App\\Controller\\EvenementsController::new()'];
        }

        return $container->privates['.service_locator.Ekf188_.App\\Controller\\EvenementsController::new()'] = $instance;
    }
}
