<?php

namespace ContainerLcL32FZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z08WQKNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z08WQKN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tache' => ['privates', '.errored..service_locator.z08WQKN.App\\Entity\\Tache', NULL, 'Cannot autowire service ".service_locator.z08WQKN": it needs an instance of "App\\Entity\\Tache" but this type has been excluded because it\'s a Doctrine entity.'],
            'domainService' => ['privates', 'App\\Service\\Domain\\PlanningDomainService', 'getPlanningDomainServiceService', true],
        ], [
            'tache' => 'App\\Entity\\Tache',
            'domainService' => 'App\\Service\\Domain\\PlanningDomainService',
        ]);

        if (isset($container->privates['.service_locator.z08WQKN'])) {
            return $container->privates['.service_locator.z08WQKN'];
        }

        return $container->privates['.service_locator.z08WQKN'] = $instance;
    }
}
