<?php

namespace ContainerLcL32FZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJournalControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j4Wlmfc.App\Controller\JournalController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j4Wlmfc.App\\Controller\\JournalController::edit()'] = ($container->privates['.service_locator.j4Wlmfc'] ?? $container->load('get_ServiceLocator_J4WlmfcService'))->withContext('App\\Controller\\JournalController::edit()', $container);
    }
}
