<?php

namespace Container99y41OT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3DuEe5oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3DuEe5o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'task' => ['privates', '.errored..service_locator.3DuEe5o.App\\Entity\\Tache', NULL, 'Cannot autowire service ".service_locator.3DuEe5o": it needs an instance of "App\\Entity\\Tache" but this type has been excluded because it\'s a Doctrine entity.'],
            'domainService' => ['privates', 'App\\Service\\Domain\\PlanningDomainService', 'getPlanningDomainServiceService', true],
        ], [
            'task' => 'App\\Entity\\Tache',
            'domainService' => 'App\\Service\\Domain\\PlanningDomainService',
        ]);

        if (isset($container->privates['.service_locator.3DuEe5o'])) {
            return $container->privates['.service_locator.3DuEe5o'];
        }

        return $container->privates['.service_locator.3DuEe5o'] = $instance;
    }
}
