<?php

namespace Container99y41OT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminMeditationControllereditConseilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZXkLKAa.App\Controller\AdminMeditationController::editConseil()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZXkLKAa.App\\Controller\\AdminMeditationController::editConseil()'] = ($container->privates['.service_locator.ZXkLKAa'] ?? $container->load('get_ServiceLocator_ZXkLKAaService'))->withContext('App\\Controller\\AdminMeditationController::editConseil()', $container);
    }
}
