<?php

namespace Container99y41OT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementsControllerexportPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OwMsx8r.App\Controller\EvenementsController::exportPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OwMsx8r.App\\Controller\\EvenementsController::exportPdf()'] = ($container->privates['.service_locator.OwMsx8r'] ?? $container->load('get_ServiceLocator_OwMsx8rService'))->withContext('App\\Controller\\EvenementsController::exportPdf()', $container);
    }
}
