<?php

namespace Container99y41OT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskApiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3DuEe5o.App\Controller\Api\TaskApiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3DuEe5o.App\\Controller\\Api\\TaskApiController::delete()'] = ($container->privates['.service_locator.3DuEe5o'] ?? $container->load('get_ServiceLocator_3DuEe5oService'))->withContext('App\\Controller\\Api\\TaskApiController::delete()', $container);
    }
}
