<?php

namespace Container5OhHtYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitesControllerapiAddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kyFosiw.App\Controller\ActivitesController::apiAdd()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'exerciceRepo' => ['privates', 'App\\Repository\\ExerciceRepository', 'getExerciceRepositoryService', true],
            'activiteRepo' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
        ], [
            'em' => '?',
            'exerciceRepo' => 'App\\Repository\\ExerciceRepository',
            'activiteRepo' => 'App\\Repository\\ActiviteRepository',
        ]))->withContext('App\\Controller\\ActivitesController::apiAdd()', $container);

        if (isset($container->privates['.service_locator.kyFosiw.App\\Controller\\ActivitesController::apiAdd()'])) {
            return $container->privates['.service_locator.kyFosiw.App\\Controller\\ActivitesController::apiAdd()'];
        }

        return $container->privates['.service_locator.kyFosiw.App\\Controller\\ActivitesController::apiAdd()'] = $instance;
    }
}
