<?php

namespace Container5OhHtYv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKanbanExportServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Export\KanbanExportService' shared autowired service.
     *
     * @return \App\Service\Export\KanbanExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Export/KanbanExportService.php';

        return $container->privates['App\\Service\\Export\\KanbanExportService'] = new \App\Service\Export\KanbanExportService();
    }
}
