<?php

namespace ContainerQkscpgf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEditUserFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AdminEditUserFormType' shared autowired service.
     *
     * @return \App\Form\AdminEditUserFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AdminEditUserFormType.php';

        return $container->privates['App\\Form\\AdminEditUserFormType'] = new \App\Form\AdminEditUserFormType();
    }
}
