<?php

namespace ContainerQkscpgf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\ChatApiController' shared autowired service.
     *
     * @return \App\Controller\Api\ChatApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/ChatApiController.php';

        $container->services['App\\Controller\\Api\\ChatApiController'] = $instance = new \App\Controller\Api\ChatApiController(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['App\\Repository\\TacheRepository'] ?? $container->load('getTacheRepositoryService')), ($container->privates['App\\Repository\\EvenementRepository'] ?? $container->load('getEvenementRepositoryService')), ($container->privates['App\\Repository\\CalendrierRepository'] ?? $container->load('getCalendrierRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\Kanban\\KanbanRealtimeNotifier'] ?? $container->load('getKanbanRealtimeNotifierService')), ($container->privates['App\\Service\\Telegram\\TelegramNotifier'] ?? $container->load('getTelegramNotifierService')), $container->getEnv('string:GEMINI_API_KEY'));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\ChatApiController', $container));

        return $instance;
    }
}
