<?php

namespace ContainerQkscpgf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventApiControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n60qnZK.App\Controller\Api\EventApiController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n60qnZK.App\\Controller\\Api\\EventApiController::list()'] = ($container->privates['.service_locator.n60qnZK'] ?? $container->load('get_ServiceLocator_N60qnZKService'))->withContext('App\\Controller\\Api\\EventApiController::list()', $container);
    }
}
