<?php

namespace ContainerQkscpgf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTachesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TachesController' shared autowired service.
     *
     * @return \App\Controller\TachesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TachesController.php';

        $container->services['App\\Controller\\TachesController'] = $instance = new \App\Controller\TachesController(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\TachesController', $container));

        return $instance;
    }
}
