<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Aliment extends \App\Entity\Aliment implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'caloriesPour100g' => [parent::class, 'caloriesPour100g', null, 16],
        "\0".parent::class."\0".'glucides' => [parent::class, 'glucides', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lipides' => [parent::class, 'lipides', null, 16],
        "\0".parent::class."\0".'nomAliment' => [parent::class, 'nomAliment', null, 16],
        "\0".parent::class."\0".'proteines' => [parent::class, 'proteines', null, 16],
        'caloriesPour100g' => [parent::class, 'caloriesPour100g', null, 16],
        'glucides' => [parent::class, 'glucides', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lipides' => [parent::class, 'lipides', null, 16],
        'nomAliment' => [parent::class, 'nomAliment', null, 16],
        'proteines' => [parent::class, 'proteines', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
