<?php

namespace ContainerDaYjFIR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventApiControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0FPZQH5.App\Controller\Api\EventApiController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'calendrierRepository' => ['privates', 'App\\Repository\\CalendrierRepository', 'getCalendrierRepositoryService', true],
            'googleService' => ['privates', 'App\\Service\\GoogleCalendarService', 'getGoogleCalendarServiceService', true],
        ], [
            'em' => '?',
            'calendrierRepository' => 'App\\Repository\\CalendrierRepository',
            'googleService' => 'App\\Service\\GoogleCalendarService',
        ]))->withContext('App\\Controller\\Api\\EventApiController::create()', $container);

        if (isset($container->privates['.service_locator.0FPZQH5.App\\Controller\\Api\\EventApiController::create()'])) {
            return $container->privates['.service_locator.0FPZQH5.App\\Controller\\Api\\EventApiController::create()'];
        }

        return $container->privates['.service_locator.0FPZQH5.App\\Controller\\Api\\EventApiController::create()'] = $instance;
    }
}
