<?php

namespace ContainerQxxn7x0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\EventApiController' shared autowired service.
     *
     * @return \App\Controller\Api\EventApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/EventApiController.php';

        $container->services['App\\Controller\\Api\\EventApiController'] = $instance = new \App\Controller\Api\EventApiController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\EventApiController', $container));

        return $instance;
    }
}
