<?php

namespace ContainerQxxn7x0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleCalendarServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GoogleCalendarService' shared autowired service.
     *
     * @return \App\Service\GoogleCalendarService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/GoogleCalendarService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\GoogleCalendarService'])) {
            return $container->privates['App\\Service\\GoogleCalendarService'];
        }

        $instance = new \App\Service\GoogleCalendarService($a, ($container->services['router'] ?? self::getRouterService($container)));

        if (isset($container->privates['App\\Service\\GoogleCalendarService'])) {
            return $container->privates['App\\Service\\GoogleCalendarService'];
        }

        return $container->privates['App\\Service\\GoogleCalendarService'] = $instance;
    }
}
