<?php

namespace ContainerQxxn7x0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleCalendarControllerconnectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n3xukcA.App\Controller\GoogleCalendarController::connect()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.n3xukcA'] ?? $container->load('get_ServiceLocator_N3xukcAService'));

        if (isset($container->privates['.service_locator.n3xukcA.App\\Controller\\GoogleCalendarController::connect()'])) {
            return $container->privates['.service_locator.n3xukcA.App\\Controller\\GoogleCalendarController::connect()'];
        }

        $instance = $a->withContext('App\\Controller\\GoogleCalendarController::connect()', $container);

        if (isset($container->privates['.service_locator.n3xukcA.App\\Controller\\GoogleCalendarController::connect()'])) {
            return $container->privates['.service_locator.n3xukcA.App\\Controller\\GoogleCalendarController::connect()'];
        }

        return $container->privates['.service_locator.n3xukcA.App\\Controller\\GoogleCalendarController::connect()'] = $instance;
    }
}
