<?php

namespace ContainerQxxn7x0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleCalendarControllerpullService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n3xukcA.App\Controller\GoogleCalendarController::pull()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n3xukcA.App\\Controller\\GoogleCalendarController::pull()'] = ($container->privates['.service_locator.n3xukcA'] ?? $container->load('get_ServiceLocator_N3xukcAService'))->withContext('App\\Controller\\GoogleCalendarController::pull()', $container);
    }
}
