<?php

namespace ContainerQxxn7x0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanningDomainServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Domain\PlanningDomainService' shared autowired service.
     *
     * @return \App\Service\Domain\PlanningDomainService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Domain/PersistenceHelper.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Domain/PlanningDomainService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Domain\\PlanningDomainService'])) {
            return $container->privates['App\\Service\\Domain\\PlanningDomainService'];
        }
        $b = ($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container));

        if (isset($container->privates['App\\Service\\Domain\\PlanningDomainService'])) {
            return $container->privates['App\\Service\\Domain\\PlanningDomainService'];
        }
        $c = ($container->privates['App\\Service\\GoogleCalendarService'] ?? $container->load('getGoogleCalendarServiceService'));

        if (isset($container->privates['App\\Service\\Domain\\PlanningDomainService'])) {
            return $container->privates['App\\Service\\Domain\\PlanningDomainService'];
        }

        $instance = new \App\Service\Domain\PlanningDomainService($a, $b, ($container->privates['App\\Repository\\DemandeReservationRepository'] ?? $container->load('getDemandeReservationRepositoryService')), ($container->privates['App\\Repository\\CalendrierRepository'] ?? $container->load('getCalendrierRepositoryService')), $c, ($container->privates['App\\Service\\Github\\GithubIssueService'] ?? $container->load('getGithubIssueServiceService')), ($container->privates['App\\Service\\Kanban\\KanbanRealtimeNotifier'] ?? $container->load('getKanbanRealtimeNotifierService')), ($container->privates['App\\Service\\Telegram\\TelegramNotifier'] ?? $container->load('getTelegramNotifierService')));

        if (isset($container->privates['App\\Service\\Domain\\PlanningDomainService'])) {
            return $container->privates['App\\Service\\Domain\\PlanningDomainService'];
        }

        return $container->privates['App\\Service\\Domain\\PlanningDomainService'] = $instance;
    }
}
