<?php

namespace ContainerQxxn7x0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionMeditationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DS21UbZ.App\Entity\SessionMeditation' shared service.
     *
     * @return \App\Entity\SessionMeditation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DS21UbZ": it needs an instance of "App\\Entity\\SessionMeditation" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
