<?php

namespace Container85ucigL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZILOSg7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZILOSg7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZILOSg7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenement' => ['privates', '.errored..service_locator.ZILOSg7.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.ZILOSg7": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
        ]);
    }
}
