<?php

namespace Container85ucigL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdminSportController' shared autowired service.
     *
     * @return \App\Controller\AdminSportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AdminSportController.php';

        $container->services['App\\Controller\\AdminSportController'] = $instance = new \App\Controller\AdminSportController(($container->privates['App\\Repository\\ExerciceRepository'] ?? $container->load('getExerciceRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\AdminSportController', $container));

        return $instance;
    }
}
