<?php

namespace Container85ucigL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rp66z6i.App\Controller\ActivitesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rp66z6i.App\\Controller\\ActivitesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exerciceRepo' => ['privates', 'App\\Repository\\ExerciceRepository', 'getExerciceRepositoryService', true],
            'activiteRepo' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
        ], [
            'exerciceRepo' => 'App\\Repository\\ExerciceRepository',
            'activiteRepo' => 'App\\Repository\\ActiviteRepository',
        ]))->withContext('App\\Controller\\ActivitesController::index()', $container);
    }
}
