<?php

namespace Container85ucigL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitesControllerapiListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z7DUdOp.App\Controller\ActivitesController::apiList()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z7DUdOp.App\\Controller\\ActivitesController::apiList()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ActiviteRepository',
        ]))->withContext('App\\Controller\\ActivitesController::apiList()', $container);
    }
}
