<?php

namespace Container85ucigL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionControllerapiJournalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eTqhGjo.App\Controller\NutritionController::apiJournal()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eTqhGjo.App\\Controller\\NutritionController::apiJournal()'] = ($container->privates['.service_locator.eTqhGjo'] ?? $container->load('get_ServiceLocator_ETqhGjoService'))->withContext('App\\Controller\\NutritionController::apiJournal()', $container);
    }
}
