<?php

namespace Container85ucigL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TacheType' shared autowired service.
     *
     * @return \App\Form\TacheType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TacheType.php';

        return $container->privates['App\\Form\\TacheType'] = new \App\Form\TacheType();
    }
}
