<?php

namespace ContainerEJhP8xA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3JdX6ziService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3JdX6zi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3JdX6zi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'github' => ['privates', 'App\\Service\\Github\\GithubIssueService', 'getGithubIssueServiceService', true],
        ], [
            'github' => 'App\\Service\\Github\\GithubIssueService',
        ]);
    }
}
