<?php

namespace ContainerEJhP8xA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSalleControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qJRwpWf.App\Controller\AdminSalleController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qJRwpWf.App\\Controller\\AdminSalleController::index()'] = ($container->privates['.service_locator.qJRwpWf'] ?? $container->load('get_ServiceLocator_QJRwpWfService'))->withContext('App\\Controller\\AdminSalleController::index()', $container);
    }
}
