<?php

namespace ContainerEJhP8xA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEvenementControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V9DAMjQ.App\Controller\AdminEvenementController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V9DAMjQ.App\\Controller\\AdminEvenementController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\AdminEvenementController::index()', $container);
    }
}
