<?php

namespace ContainerEJhP8xA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGithubSettingsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\GithubSettingsController' shared autowired service.
     *
     * @return \App\Controller\Api\GithubSettingsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/GithubSettingsController.php';

        $container->services['App\\Controller\\Api\\GithubSettingsController'] = $instance = new \App\Controller\Api\GithubSettingsController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\GithubSettingsController', $container));

        return $instance;
    }
}
