<?php

namespace ContainerEJhP8xA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKanbanRealtimeNotifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Kanban\KanbanRealtimeNotifier' shared autowired service.
     *
     * @return \App\Service\Kanban\KanbanRealtimeNotifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Kanban/KanbanRealtimeNotifier.php';

        return $container->privates['App\\Service\\Kanban\\KanbanRealtimeNotifier'] = new \App\Service\Kanban\KanbanRealtimeNotifier(($container->services['cache.app'] ?? self::getCache_AppService($container)));
    }
}
