<?php

namespace ContainerXi8Jbhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WbJQk76Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WbJQk76' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'salle' => ['privates', '.errored..service_locator.WbJQk76.App\\Entity\\Salle', NULL, 'Cannot autowire service ".service_locator.WbJQk76": it needs an instance of "App\\Entity\\Salle" but this type has been excluded because it\'s a Doctrine entity.'],
            'domainService' => ['privates', 'App\\Service\\Domain\\PlanningDomainService', 'getPlanningDomainServiceService', true],
        ], [
            'salle' => 'App\\Entity\\Salle',
            'domainService' => 'App\\Service\\Domain\\PlanningDomainService',
        ]);

        if (isset($container->privates['.service_locator.WbJQk76'])) {
            return $container->privates['.service_locator.WbJQk76'];
        }

        return $container->privates['.service_locator.WbJQk76'] = $instance;
    }
}
