<?php

namespace ContainerXi8Jbhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GRbyOdQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gRbyOdQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'activiteRepo' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
        ], [
            'em' => '?',
            'activiteRepo' => 'App\\Repository\\ActiviteRepository',
        ]);

        if (isset($container->privates['.service_locator.gRbyOdQ'])) {
            return $container->privates['.service_locator.gRbyOdQ'];
        }

        return $container->privates['.service_locator.gRbyOdQ'] = $instance;
    }
}
