<?php

namespace ContainerXi8Jbhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GsKU6fYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GsKU6fY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.GsKU6fY.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.GsKU6fY": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'googleService' => ['privates', 'App\\Service\\GoogleCalendarService', 'getGoogleCalendarServiceService', true],
        ], [
            'event' => 'App\\Entity\\Evenement',
            'em' => '?',
            'googleService' => 'App\\Service\\GoogleCalendarService',
        ]);

        if (isset($container->privates['.service_locator.GsKU6fY'])) {
            return $container->privates['.service_locator.GsKU6fY'];
        }

        return $container->privates['.service_locator.GsKU6fY'] = $instance;
    }
}
