<?php

namespace ContainerXi8Jbhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OwMsx8rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OwMsx8r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OwMsx8r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'exportService' => ['privates', 'App\\Service\\Export\\CalendarExportService', 'getCalendarExportServiceService', true],
        ], [
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
            'exportService' => 'App\\Service\\Export\\CalendarExportService',
        ]);
    }
}
