<?php

namespace ContainerXi8Jbhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEvenementControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NsUdOW3.App\Controller\AdminEvenementController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NsUdOW3.App\\Controller\\AdminEvenementController::delete()'] = ($container->privates['.service_locator.NsUdOW3'] ?? $container->load('get_ServiceLocator_NsUdOW3Service'))->withContext('App\\Controller\\AdminEvenementController::delete()', $container);
    }
}
