<?php

namespace ContainerXi8Jbhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminMeditationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DS21UbZ.App\Controller\AdminMeditationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DS21UbZ.App\\Controller\\AdminMeditationController::edit()'] = ($container->privates['.service_locator.DS21UbZ'] ?? $container->load('get_ServiceLocator_DS21UbZService'))->withContext('App\\Controller\\AdminMeditationController::edit()', $container);
    }
}
