<?php

namespace ContainerXi8Jbhp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionControllerapiSupprimerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uw2k5kr.App\Controller\NutritionController::apiSupprimer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Uw2k5kr'] ?? $container->load('get_ServiceLocator_Uw2k5krService'));

        if (isset($container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiSupprimer()'])) {
            return $container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiSupprimer()'];
        }

        $instance = $a->withContext('App\\Controller\\NutritionController::apiSupprimer()', $container);

        if (isset($container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiSupprimer()'])) {
            return $container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiSupprimer()'];
        }

        return $container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiSupprimer()'] = $instance;
    }
}
