<?php

namespace Container35fvxxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ETqhGjoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eTqhGjo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eTqhGjo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consRepo' => ['privates', 'App\\Repository\\ConsommationRepository', 'getConsommationRepositoryService', true],
        ], [
            'consRepo' => 'App\\Repository\\ConsommationRepository',
        ]);
    }
}
