<?php

namespace Container35fvxxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitesControllerapiDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gRbyOdQ.App\Controller\ActivitesController::apiDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.gRbyOdQ'] ?? $container->load('get_ServiceLocator_GRbyOdQService'));

        if (isset($container->privates['.service_locator.gRbyOdQ.App\\Controller\\ActivitesController::apiDelete()'])) {
            return $container->privates['.service_locator.gRbyOdQ.App\\Controller\\ActivitesController::apiDelete()'];
        }

        $instance = $a->withContext('App\\Controller\\ActivitesController::apiDelete()', $container);

        if (isset($container->privates['.service_locator.gRbyOdQ.App\\Controller\\ActivitesController::apiDelete()'])) {
            return $container->privates['.service_locator.gRbyOdQ.App\\Controller\\ActivitesController::apiDelete()'];
        }

        return $container->privates['.service_locator.gRbyOdQ.App\\Controller\\ActivitesController::apiDelete()'] = $instance;
    }
}
