<?php

namespace Container35fvxxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.beXXK0P.App\Controller\AdminDashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.beXXK0P.App\\Controller\\AdminDashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'suspicion' => ['privates', 'App\\Service\\SuspicionScoreService', 'getSuspicionScoreServiceService', true],
        ], [
            'repo' => 'App\\Repository\\UserRepository',
            'suspicion' => 'App\\Service\\SuspicionScoreService',
        ]))->withContext('App\\Controller\\AdminDashboardController::index()', $container);
    }
}
