<?php

namespace Container35fvxxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ziqo37J.App\Controller\BackController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ziqo37J.App\\Controller\\BackController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'comRepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
        ], [
            'catRepo' => 'App\\Repository\\CategorieRepository',
            'postRepo' => 'App\\Repository\\PostRepository',
            'comRepo' => 'App\\Repository\\CommentaireRepository',
        ]))->withContext('App\\Controller\\BackController::dashboard()', $container);
    }
}
