<?php

namespace Container35fvxxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionControllerapiAjouterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9SYQ8z3.App\Controller\NutritionController::apiAjouter()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'alimentRepo' => ['privates', 'App\\Repository\\AlimentRepository', 'getAlimentRepositoryService', true],
            'consRepo' => ['privates', 'App\\Repository\\ConsommationRepository', 'getConsommationRepositoryService', true],
        ], [
            'em' => '?',
            'alimentRepo' => 'App\\Repository\\AlimentRepository',
            'consRepo' => 'App\\Repository\\ConsommationRepository',
        ]))->withContext('App\\Controller\\NutritionController::apiAjouter()', $container);

        if (isset($container->privates['.service_locator.9SYQ8z3.App\\Controller\\NutritionController::apiAjouter()'])) {
            return $container->privates['.service_locator.9SYQ8z3.App\\Controller\\NutritionController::apiAjouter()'];
        }

        return $container->privates['.service_locator.9SYQ8z3.App\\Controller\\NutritionController::apiAjouter()'] = $instance;
    }
}
