<?php

namespace Container35fvxxS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterStep2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wEoPZVd.App\Controller\RegistrationController::registerStep2()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.wEoPZVd'] ?? $container->load('get_ServiceLocator_WEoPZVdService'));

        if (isset($container->privates['.service_locator.wEoPZVd.App\\Controller\\RegistrationController::registerStep2()'])) {
            return $container->privates['.service_locator.wEoPZVd.App\\Controller\\RegistrationController::registerStep2()'];
        }

        $instance = $a->withContext('App\\Controller\\RegistrationController::registerStep2()', $container);

        if (isset($container->privates['.service_locator.wEoPZVd.App\\Controller\\RegistrationController::registerStep2()'])) {
            return $container->privates['.service_locator.wEoPZVd.App\\Controller\\RegistrationController::registerStep2()'];
        }

        return $container->privates['.service_locator.wEoPZVd.App\\Controller\\RegistrationController::registerStep2()'] = $instance;
    }
}
