<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \App\Entity\Evenement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'approuve' => [parent::class, 'approuve', null, 16],
        "\0".parent::class."\0".'calendrier' => [parent::class, 'calendrier', null, 16],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null, 16],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null, 16],
        "\0".parent::class."\0".'demandeReservations' => [parent::class, 'demandeReservations', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'eventType' => [parent::class, 'eventType', null, 16],
        "\0".parent::class."\0".'googleEventId' => [parent::class, 'googleEventId', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lieu' => [parent::class, 'lieu', null, 16],
        "\0".parent::class."\0".'lieuAdresse' => [parent::class, 'lieuAdresse', null, 16],
        "\0".parent::class."\0".'lieuType' => [parent::class, 'lieuType', null, 16],
        "\0".parent::class."\0".'priorite' => [parent::class, 'priorite', null, 16],
        "\0".parent::class."\0".'proprietaire' => [parent::class, 'proprietaire', null, 16],
        "\0".parent::class."\0".'rappelActif' => [parent::class, 'rappelActif', null, 16],
        "\0".parent::class."\0".'salle' => [parent::class, 'salle', null, 16],
        "\0".parent::class."\0".'statutDemandeSalle' => [parent::class, 'statutDemandeSalle', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        "\0".parent::class."\0".'typeEvenement' => [parent::class, 'typeEvenement', null, 16],
        'approuve' => [parent::class, 'approuve', null, 16],
        'calendrier' => [parent::class, 'calendrier', null, 16],
        'dateDebut' => [parent::class, 'dateDebut', null, 16],
        'dateFin' => [parent::class, 'dateFin', null, 16],
        'demandeReservations' => [parent::class, 'demandeReservations', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'eventType' => [parent::class, 'eventType', null, 16],
        'googleEventId' => [parent::class, 'googleEventId', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lieu' => [parent::class, 'lieu', null, 16],
        'lieuAdresse' => [parent::class, 'lieuAdresse', null, 16],
        'lieuType' => [parent::class, 'lieuType', null, 16],
        'priorite' => [parent::class, 'priorite', null, 16],
        'proprietaire' => [parent::class, 'proprietaire', null, 16],
        'rappelActif' => [parent::class, 'rappelActif', null, 16],
        'salle' => [parent::class, 'salle', null, 16],
        'statutDemandeSalle' => [parent::class, 'statutDemandeSalle', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
        'typeEvenement' => [parent::class, 'typeEvenement', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
