<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateInscription' => [parent::class, 'dateInscription', null, 16],
        "\0".parent::class."\0".'faceIdEnabled' => [parent::class, 'faceIdEnabled', null, 16],
        "\0".parent::class."\0".'faceImagePath' => [parent::class, 'faceImagePath', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'typeUtilisateur' => [parent::class, 'typeUtilisateur', null, 16],
        "\0".parent::class."\0".'userDateDeNaissance' => [parent::class, 'userDateDeNaissance', null, 16],
        "\0".parent::class."\0".'userEmail' => [parent::class, 'userEmail', null, 16],
        "\0".parent::class."\0".'userEtablissementScolaire' => [parent::class, 'userEtablissementScolaire', null, 16],
        "\0".parent::class."\0".'userId' => [parent::class, 'userId', null, 16],
        "\0".parent::class."\0".'userImagePath' => [parent::class, 'userImagePath', null, 16],
        "\0".parent::class."\0".'userNiveauActivitePhysique' => [parent::class, 'userNiveauActivitePhysique', null, 16],
        "\0".parent::class."\0".'userNiveauScolaire' => [parent::class, 'userNiveauScolaire', null, 16],
        "\0".parent::class."\0".'userNom' => [parent::class, 'userNom', null, 16],
        "\0".parent::class."\0".'userPassword' => [parent::class, 'userPassword', null, 16],
        "\0".parent::class."\0".'userPoids' => [parent::class, 'userPoids', null, 16],
        "\0".parent::class."\0".'userPrenom' => [parent::class, 'userPrenom', null, 16],
        "\0".parent::class."\0".'userSexe' => [parent::class, 'userSexe', null, 16],
        "\0".parent::class."\0".'userTaille' => [parent::class, 'userTaille', null, 16],
        'dateInscription' => [parent::class, 'dateInscription', null, 16],
        'faceIdEnabled' => [parent::class, 'faceIdEnabled', null, 16],
        'faceImagePath' => [parent::class, 'faceImagePath', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'typeUtilisateur' => [parent::class, 'typeUtilisateur', null, 16],
        'userDateDeNaissance' => [parent::class, 'userDateDeNaissance', null, 16],
        'userEmail' => [parent::class, 'userEmail', null, 16],
        'userEtablissementScolaire' => [parent::class, 'userEtablissementScolaire', null, 16],
        'userId' => [parent::class, 'userId', null, 16],
        'userImagePath' => [parent::class, 'userImagePath', null, 16],
        'userNiveauActivitePhysique' => [parent::class, 'userNiveauActivitePhysique', null, 16],
        'userNiveauScolaire' => [parent::class, 'userNiveauScolaire', null, 16],
        'userNom' => [parent::class, 'userNom', null, 16],
        'userPassword' => [parent::class, 'userPassword', null, 16],
        'userPoids' => [parent::class, 'userPoids', null, 16],
        'userPrenom' => [parent::class, 'userPrenom', null, 16],
        'userSexe' => [parent::class, 'userSexe', null, 16],
        'userTaille' => [parent::class, 'userTaille', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
