<?php

namespace ContainerUoxydQY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uw2k5krService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uw2k5kr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'consRepo' => ['privates', 'App\\Repository\\ConsommationRepository', 'getConsommationRepositoryService', true],
        ], [
            'em' => '?',
            'consRepo' => 'App\\Repository\\ConsommationRepository',
        ]);

        if (isset($container->privates['.service_locator.Uw2k5kr'])) {
            return $container->privates['.service_locator.Uw2k5kr'];
        }

        return $container->privates['.service_locator.Uw2k5kr'] = $instance;
    }
}
