<?php

namespace ContainerO9WDWHe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUserControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UoveXVI.App\Controller\AdminUserController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UoveXVI.App\\Controller\\AdminUserController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.UoveXVI.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.UoveXVI": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\AdminUserController::edit()', $container);
    }
}
