<?php

namespace Container59TPerr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DS21UbZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DS21UbZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DS21UbZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'session' => ['privates', '.errored..service_locator.DS21UbZ.App\\Entity\\SessionMeditation', NULL, 'Cannot autowire service ".service_locator.DS21UbZ": it needs an instance of "App\\Entity\\SessionMeditation" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'session' => 'App\\Entity\\SessionMeditation',
        ]);
    }
}
