<?php

namespace Container59TPerr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NsUdOW3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NsUdOW3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenement' => ['privates', '.errored..service_locator.NsUdOW3.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.NsUdOW3": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded because it\'s a Doctrine entity.'],
            'domainService' => ['privates', 'App\\Service\\Domain\\PlanningDomainService', 'getPlanningDomainServiceService', true],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
            'domainService' => 'App\\Service\\Domain\\PlanningDomainService',
        ]);

        if (isset($container->privates['.service_locator.NsUdOW3'])) {
            return $container->privates['.service_locator.NsUdOW3'];
        }

        return $container->privates['.service_locator.NsUdOW3'] = $instance;
    }
}
