<?php

namespace Container59TPerr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUserControllersuspicionDetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kYAceIU.App\Controller\AdminUserController::suspicionDetail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kYAceIU.App\\Controller\\AdminUserController::suspicionDetail()'] = ($container->privates['.service_locator.kYAceIU'] ?? $container->load('get_ServiceLocator_KYAceIUService'))->withContext('App\\Controller\\AdminUserController::suspicionDetail()', $container);
    }
}
