<?php

namespace Container59TPerr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGithubSettingsControllergetSettingsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3JdX6zi.App\Controller\Api\GithubSettingsController::getSettings()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3JdX6zi.App\\Controller\\Api\\GithubSettingsController::getSettings()'] = ($container->privates['.service_locator.3JdX6zi'] ?? $container->load('get_ServiceLocator_3JdX6ziService'))->withContext('App\\Controller\\Api\\GithubSettingsController::getSettings()', $container);
    }
}
