<?php

namespace ContainerE5IUEkW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackControllerdeletePostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M54_pAu.App\Controller\BackController::deletePost()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'postRepo' => 'App\\Repository\\PostRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\BackController::deletePost()', $container);

        if (isset($container->privates['.service_locator.M54_pAu.App\\Controller\\BackController::deletePost()'])) {
            return $container->privates['.service_locator.M54_pAu.App\\Controller\\BackController::deletePost()'];
        }

        return $container->privates['.service_locator.M54_pAu.App\\Controller\\BackController::deletePost()'] = $instance;
    }
}
