<?php

namespace ContainerE5IUEkW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGithubSettingsControllersyncDoingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B003gDi.App\Controller\Api\GithubSettingsController::syncDoing()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B003gDi.App\\Controller\\Api\\GithubSettingsController::syncDoing()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'github' => ['privates', 'App\\Service\\Github\\GithubIssueService', 'getGithubIssueServiceService', true],
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'github' => 'App\\Service\\Github\\GithubIssueService',
            'tacheRepository' => 'App\\Repository\\TacheRepository',
        ]))->withContext('App\\Controller\\Api\\GithubSettingsController::syncDoing()', $container);
    }
}
