<?php

namespace ContainerE5IUEkW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGithubIssueServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Github\GithubIssueService' shared autowired service.
     *
     * @return \App\Service\Github\GithubIssueService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Github/GithubIssueService.php';

        return $container->privates['App\\Service\\Github\\GithubIssueService'] = new \App\Service\Github\GithubIssueService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), \dirname(__DIR__, 4), $container->getEnv('string:GITHUB_PAT'), $container->getEnv('string:GITHUB_REPO'), $container->getEnv('string:GITHUB_BRANCH'));
    }
}
