<?php

namespace ContainerE5IUEkW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEventRemindersCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SendEventRemindersCommand' shared autowired service.
     *
     * @return \App\Command\SendEventRemindersCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SendEventRemindersCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Telegram/EventReminderService.php';

        $a = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $container->privates['App\\Command\\SendEventRemindersCommand'] = $instance = new \App\Command\SendEventRemindersCommand(($container->privates['App\\Repository\\EvenementRepository'] ?? $container->load('getEvenementRepositoryService')), new \App\Service\Telegram\EventReminderService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), $a, $container->getEnv('string:TELEGRAM_BOT_TOKEN')), $a);

        $instance->setName('app:events:send-reminders');
        $instance->setDescription('Envoie les rappels Telegram 15 minutes avant les événements.');

        return $instance;
    }
}
