<?php

namespace ContainerE5IUEkW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramNotifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Telegram\TelegramNotifier' shared autowired service.
     *
     * @return \App\Service\Telegram\TelegramNotifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Telegram/TelegramNotifier.php';

        return $container->privates['App\\Service\\Telegram\\TelegramNotifier'] = new \App\Service\Telegram\TelegramNotifier(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $container->getEnv('string:TELEGRAM_BOT_TOKEN'), $container->getEnv('string:TELEGRAM_CHAT_ID'));
    }
}
