<?php

namespace ContainerXa0zt6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AJCrrkcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AJCrrkc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.AJCrrkc.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.AJCrrkc": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'event' => 'App\\Entity\\Evenement',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.AJCrrkc'])) {
            return $container->privates['.service_locator.AJCrrkc'];
        }

        return $container->privates['.service_locator.AJCrrkc'] = $instance;
    }
}
