<?php

namespace ContainerXa0zt6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUserControllertoggleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kYAceIU.App\Controller\AdminUserController::toggle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kYAceIU.App\\Controller\\AdminUserController::toggle()'] = ($container->privates['.service_locator.kYAceIU'] ?? $container->load('get_ServiceLocator_KYAceIUService'))->withContext('App\\Controller\\AdminUserController::toggle()', $container);
    }
}
