<?php

namespace ContainerXa0zt6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionControllerapiAlimentsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jFG7qVJ.App\Controller\NutritionController::apiAliments()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jFG7qVJ.App\\Controller\\NutritionController::apiAliments()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\AlimentRepository', 'getAlimentRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\AlimentRepository',
        ]))->withContext('App\\Controller\\NutritionController::apiAliments()', $container);
    }
}
