<?php

namespace ContainerXa0zt6X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuspicionScoreServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SuspicionScoreService' shared autowired service.
     *
     * @return \App\Service\SuspicionScoreService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SuspicionScoreService.php';

        return $container->privates['App\\Service\\SuspicionScoreService'] = new \App\Service\SuspicionScoreService();
    }
}
