<?php

namespace ContainerB3SpCdh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TqdrIWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tqdr_iW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demande' => ['privates', '.errored..service_locator.tqdr_iW.App\\Entity\\DemandeReservation', NULL, 'Cannot autowire service ".service_locator.tqdr_iW": it needs an instance of "App\\Entity\\DemandeReservation" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'demande' => 'App\\Entity\\DemandeReservation',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.tqdr_iW'])) {
            return $container->privates['.service_locator.tqdr_iW'];
        }

        return $container->privates['.service_locator.tqdr_iW'] = $instance;
    }
}
