<?php

namespace ContainerB3SpCdh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZXkLKAaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZXkLKAa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZXkLKAa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conseil' => ['privates', '.errored..service_locator.ZXkLKAa.App\\Entity\\Conseil', NULL, 'Cannot autowire service ".service_locator.ZXkLKAa": it needs an instance of "App\\Entity\\Conseil" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'conseil' => 'App\\Entity\\Conseil',
        ]);
    }
}
