<?php

namespace ContainerB3SpCdh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminTacheControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z08WQKN.App\Controller\AdminTacheController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z08WQKN.App\\Controller\\AdminTacheController::delete()'] = ($container->privates['.service_locator.z08WQKN'] ?? $container->load('get_ServiceLocator_Z08WQKNService'))->withContext('App\\Controller\\AdminTacheController::delete()', $container);
    }
}
