<?php

namespace ContainerB3SpCdh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConseilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZXkLKAa.App\Entity\Conseil' shared service.
     *
     * @return \App\Entity\Conseil
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZXkLKAa": it needs an instance of "App\\Entity\\Conseil" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
