<?php

namespace ContainerB3SpCdh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementsControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NgPr0wp.App\Controller\EvenementsController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NgPr0wp.App\\Controller\\EvenementsController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'calendrierRepository' => ['privates', 'App\\Repository\\CalendrierRepository', 'getCalendrierRepositoryService', true],
        ], [
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
            'calendrierRepository' => 'App\\Repository\\CalendrierRepository',
        ]))->withContext('App\\Controller\\EvenementsController::index()', $container);
    }
}
