<?php

namespace ContainerB3SpCdh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJournalHumeurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.j4Wlmfc.App\Entity\JournalHumeur' shared service.
     *
     * @return \App\Entity\JournalHumeur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.j4Wlmfc": it needs an instance of "App\\Entity\\JournalHumeur" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
