<?php

namespace ContainerB3SpCdh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionControllerapiModifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uw2k5kr.App\Controller\NutritionController::apiModifier()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Uw2k5kr'] ?? $container->load('get_ServiceLocator_Uw2k5krService'));

        if (isset($container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiModifier()'])) {
            return $container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiModifier()'];
        }

        $instance = $a->withContext('App\\Controller\\NutritionController::apiModifier()', $container);

        if (isset($container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiModifier()'])) {
            return $container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiModifier()'];
        }

        return $container->privates['.service_locator.Uw2k5kr.App\\Controller\\NutritionController::apiModifier()'] = $instance;
    }
}
