<?php

namespace ContainerB3SpCdh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskApiControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PUfitXC.App\Controller\Api\TaskApiController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.PUfitXC'] ?? $container->load('get_ServiceLocator_PUfitXCService'));

        if (isset($container->privates['.service_locator.PUfitXC.App\\Controller\\Api\\TaskApiController::create()'])) {
            return $container->privates['.service_locator.PUfitXC.App\\Controller\\Api\\TaskApiController::create()'];
        }

        $instance = $a->withContext('App\\Controller\\Api\\TaskApiController::create()', $container);

        if (isset($container->privates['.service_locator.PUfitXC.App\\Controller\\Api\\TaskApiController::create()'])) {
            return $container->privates['.service_locator.PUfitXC.App\\Controller\\Api\\TaskApiController::create()'];
        }

        return $container->privates['.service_locator.PUfitXC.App\\Controller\\Api\\TaskApiController::create()'] = $instance;
    }
}
