<?php

namespace ContainerYF5J2E2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDemandeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lUtuGUv.App\Controller\AdminDemandeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lUtuGUv.App\\Controller\\AdminDemandeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'demandeReservationRepository' => ['privates', 'App\\Repository\\DemandeReservationRepository', 'getDemandeReservationRepositoryService', true],
        ], [
            'demandeReservationRepository' => 'App\\Repository\\DemandeReservationRepository',
        ]))->withContext('App\\Controller\\AdminDemandeController::index()', $container);
    }
}
