<?php

namespace ContainerYF5J2E2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackControllercategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y_R0bCX.App\Controller\BackController::categories()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y_R0bCX.App\\Controller\\BackController::categories()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'catRepo' => 'App\\Repository\\CategorieRepository',
            'postRepo' => 'App\\Repository\\PostRepository',
        ]))->withContext('App\\Controller\\BackController::categories()', $container);
    }
}
