<?php

namespace ContainerYF5J2E2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNutritionControllerajouterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cz8IWeY.App\Controller\NutritionController::ajouter()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cz8IWeY.App\\Controller\\NutritionController::ajouter()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alimentRepo' => ['privates', 'App\\Repository\\AlimentRepository', 'getAlimentRepositoryService', true],
        ], [
            'alimentRepo' => 'App\\Repository\\AlimentRepository',
        ]))->withContext('App\\Controller\\NutritionController::ajouter()', $container);
    }
}
