<?php

namespace ContainerGcRKzpX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vt5yBu_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vt5yBu.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vt5yBu.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
            'exportService' => ['privates', 'App\\Service\\Export\\KanbanExportService', 'getKanbanExportServiceService', true],
        ], [
            'tacheRepository' => 'App\\Repository\\TacheRepository',
            'exportService' => 'App\\Service\\Export\\KanbanExportService',
        ]);
    }
}
