<?php

namespace ContainerGcRKzpX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackControllercommentairesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hr1mps8.App\Controller\BackController::commentaires()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hr1mps8.App\\Controller\\BackController::commentaires()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comRepo' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
        ], [
            'comRepo' => 'App\\Repository\\CommentaireRepository',
        ]))->withContext('App\\Controller\\BackController::commentaires()', $container);
    }
}
