<?php

namespace ContainerGcRKzpX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarExportServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Export\CalendarExportService' shared autowired service.
     *
     * @return \App\Service\Export\CalendarExportService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Export'.\DIRECTORY_SEPARATOR.'CalendarExportService.php';

        return $container->privates['App\\Service\\Export\\CalendarExportService'] = new \App\Service\Export\CalendarExportService();
    }
}
