<?php

namespace ContainerGcRKzpX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeditationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MeditationController' shared autowired service.
     *
     * @return \App\Controller\MeditationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'MeditationController.php';

        $container->services['App\\Controller\\MeditationController'] = $instance = new \App\Controller\MeditationController(($container->privates['App\\Repository\\SessionMeditationRepository'] ?? $container->load('getSessionMeditationRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\MeditationController', $container));

        return $instance;
    }
}
