<?php

namespace ContainerGcRKzpX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTachesControllerexportCsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e53I5WH.App\Controller\TachesController::exportCsv()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e53I5WH.App\\Controller\\TachesController::exportCsv()'] = ($container->privates['.service_locator.e53I5WH'] ?? $container->load('get_ServiceLocator_E53I5WHService'))->withContext('App\\Controller\\TachesController::exportCsv()', $container);
    }
}
