<?php

namespace ContainerYmpTVxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDemandeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdminDemandeController' shared autowired service.
     *
     * @return \App\Controller\AdminDemandeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AdminDemandeController.php';

        $container->services['App\\Controller\\AdminDemandeController'] = $instance = new \App\Controller\AdminDemandeController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\AdminDemandeController', $container));

        return $instance;
    }
}
