<?php

namespace ContainerYmpTVxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminTacheControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z08WQKN.App\Controller\AdminTacheController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.z08WQKN'] ?? $container->load('get_ServiceLocator_Z08WQKNService'));

        if (isset($container->privates['.service_locator.z08WQKN.App\\Controller\\AdminTacheController::edit()'])) {
            return $container->privates['.service_locator.z08WQKN.App\\Controller\\AdminTacheController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\AdminTacheController::edit()', $container);

        if (isset($container->privates['.service_locator.z08WQKN.App\\Controller\\AdminTacheController::edit()'])) {
            return $container->privates['.service_locator.z08WQKN.App\\Controller\\AdminTacheController::edit()'];
        }

        return $container->privates['.service_locator.z08WQKN.App\\Controller\\AdminTacheController::edit()'] = $instance;
    }
}
