<?php

namespace ContainerYmpTVxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSalleControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WbJQk76.App\Controller\AdminSalleController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.WbJQk76'] ?? $container->load('get_ServiceLocator_WbJQk76Service'));

        if (isset($container->privates['.service_locator.WbJQk76.App\\Controller\\AdminSalleController::edit()'])) {
            return $container->privates['.service_locator.WbJQk76.App\\Controller\\AdminSalleController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\AdminSalleController::edit()', $container);

        if (isset($container->privates['.service_locator.WbJQk76.App\\Controller\\AdminSalleController::edit()'])) {
            return $container->privates['.service_locator.WbJQk76.App\\Controller\\AdminSalleController::edit()'];
        }

        return $container->privates['.service_locator.WbJQk76.App\\Controller\\AdminSalleController::edit()'] = $instance;
    }
}
