<?php

namespace ContainerYmpTVxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementsControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZILOSg7.App\Controller\EvenementsController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZILOSg7.App\\Controller\\EvenementsController::show()'] = ($container->privates['.service_locator.ZILOSg7'] ?? $container->load('get_ServiceLocator_ZILOSg7Service'))->withContext('App\\Controller\\EvenementsController::show()', $container);
    }
}
