<?php

namespace ContainerYmpTVxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJournalHumeurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\JournalHumeurType' shared autowired service.
     *
     * @return \App\Form\JournalHumeurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/JournalHumeurType.php';

        return $container->privates['App\\Form\\JournalHumeurType'] = new \App\Form\JournalHumeurType();
    }
}
