<?php

namespace ContainerYmpTVxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKanbanStreamControllereventsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9XNXc6E.App\Controller\Api\KanbanStreamController::events()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9XNXc6E.App\\Controller\\Api\\KanbanStreamController::events()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notifier' => ['privates', 'App\\Service\\Kanban\\KanbanRealtimeNotifier', 'getKanbanRealtimeNotifierService', true],
        ], [
            'notifier' => 'App\\Service\\Kanban\\KanbanRealtimeNotifier',
        ]))->withContext('App\\Controller\\Api\\KanbanStreamController::events()', $container);
    }
}
