<?php

namespace ContainerKsvASVm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTachesControllerexportExcelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vt5yBu..App\Controller\TachesController::exportExcel()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vt5yBu..App\\Controller\\TachesController::exportExcel()'] = ($container->privates['.service_locator.Vt5yBu.'] ?? $container->load('get_ServiceLocator_Vt5yBu_Service'))->withContext('App\\Controller\\TachesController::exportExcel()', $container);
    }
}
