<?php

namespace ContainerSdlxNJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminTacheControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GVgECGd.App\Controller\AdminTacheController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GVgECGd.App\\Controller\\AdminTacheController::show()'] = ($container->privates['.service_locator.GVgECGd'] ?? $container->load('get_ServiceLocator_GVgECGdService'))->withContext('App\\Controller\\AdminTacheController::show()', $container);
    }
}
