<?php

namespace ContainerSdlxNJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackControllerpostsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0qCImsD.App\Controller\BackController::posts()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0qCImsD.App\\Controller\\BackController::posts()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'postRepo' => 'App\\Repository\\PostRepository',
            'catRepo' => 'App\\Repository\\CategorieRepository',
        ]))->withContext('App\\Controller\\BackController::posts()', $container);
    }
}
