<?php

namespace ContainerSdlxNJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenementsControllerexportCsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n60qnZK.App\Controller\EvenementsController::exportCsv()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n60qnZK.App\\Controller\\EvenementsController::exportCsv()'] = ($container->privates['.service_locator.n60qnZK'] ?? $container->load('get_ServiceLocator_N60qnZKService'))->withContext('App\\Controller\\EvenementsController::exportCsv()', $container);
    }
}
