<?php

namespace ContainerSdlxNJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventApiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IM4O4EN.App\Controller\Api\EventApiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.IM4O4EN'] ?? $container->load('get_ServiceLocator_IM4O4ENService'));

        if (isset($container->privates['.service_locator.IM4O4EN.App\\Controller\\Api\\EventApiController::delete()'])) {
            return $container->privates['.service_locator.IM4O4EN.App\\Controller\\Api\\EventApiController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Api\\EventApiController::delete()', $container);

        if (isset($container->privates['.service_locator.IM4O4EN.App\\Controller\\Api\\EventApiController::delete()'])) {
            return $container->privates['.service_locator.IM4O4EN.App\\Controller\\Api\\EventApiController::delete()'];
        }

        return $container->privates['.service_locator.IM4O4EN.App\\Controller\\Api\\EventApiController::delete()'] = $instance;
    }
}
