<?php

namespace ContainerSdlxNJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGithubWebhookControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\GithubWebhookController' shared autowired service.
     *
     * @return \App\Controller\Api\GithubWebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/GithubWebhookController.php';

        $container->services['App\\Controller\\Api\\GithubWebhookController'] = $instance = new \App\Controller\Api\GithubWebhookController($container->getEnv('string:GITHUB_WEBHOOK_SECRET'));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Api\\GithubWebhookController', $container));

        return $instance;
    }
}
