<?php

namespace ContainerSdlxNJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGithubWebhookControllerInvokeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nl1UqvZ.App\Controller\Api\GithubWebhookController::__invoke()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
            'calendrierRepository' => ['privates', 'App\\Repository\\CalendrierRepository', 'getCalendrierRepositoryService', true],
            'githubService' => ['privates', 'App\\Service\\Github\\GithubIssueService', 'getGithubIssueServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notifier' => ['privates', 'App\\Service\\Kanban\\KanbanRealtimeNotifier', 'getKanbanRealtimeNotifierService', true],
        ], [
            'tacheRepository' => 'App\\Repository\\TacheRepository',
            'calendrierRepository' => 'App\\Repository\\CalendrierRepository',
            'githubService' => 'App\\Service\\Github\\GithubIssueService',
            'em' => '?',
            'notifier' => 'App\\Service\\Kanban\\KanbanRealtimeNotifier',
        ]))->withContext('App\\Controller\\Api\\GithubWebhookController::__invoke()', $container);

        if (isset($container->privates['.service_locator.Nl1UqvZ.App\\Controller\\Api\\GithubWebhookController::__invoke()'])) {
            return $container->privates['.service_locator.Nl1UqvZ.App\\Controller\\Api\\GithubWebhookController::__invoke()'];
        }

        return $container->privates['.service_locator.Nl1UqvZ.App\\Controller\\Api\\GithubWebhookController::__invoke()'] = $instance;
    }
}
