<?php

namespace ContainerSdlxNJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendEventRemindersCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SendEventRemindersCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SendEventRemindersCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:events:send-reminders', [], 'Envoie les rappels Telegram selon le délai choisi par événement.', false, #[\Closure(name: 'App\\Command\\SendEventRemindersCommand')] fn (): \App\Command\SendEventRemindersCommand => ($container->privates['App\\Command\\SendEventRemindersCommand'] ?? $container->load('getSendEventRemindersCommandService')));
    }
}
