<?php

namespace ContainerSdlxNJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTache2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GVgECGd.App\Entity\Tache' shared service.
     *
     * @return \App\Entity\Tache
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GVgECGd": it needs an instance of "App\\Entity\\Tache" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
