<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container99y41OT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container99y41OT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container99y41OT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container99y41OT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container99y41OT\App_KernelDevDebugContainer([
    'container.build_hash' => '99y41OT',
    'container.build_id' => 'd215ccd0',
    'container.build_time' => 1776085652,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container99y41OT');
