<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoxydQY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoxydQY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoxydQY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoxydQY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUoxydQY\App_KernelDevDebugContainer([
    'container.build_hash' => 'UoxydQY',
    'container.build_id' => '180ba551',
    'container.build_time' => 1776038295,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoxydQY');
