<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB3SpCdh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB3SpCdh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB3SpCdh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB3SpCdh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB3SpCdh\App_KernelDevDebugContainer([
    'container.build_hash' => 'B3SpCdh',
    'container.build_id' => 'af9b08d4',
    'container.build_time' => 1775871730,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB3SpCdh');
