<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcRKzpX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcRKzpX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcRKzpX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcRKzpX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGcRKzpX\App_KernelDevDebugContainer([
    'container.build_hash' => 'GcRKzpX',
    'container.build_id' => '70c90076',
    'container.build_time' => 1775459502,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcRKzpX');
